# Generated by Django 3.2.1 on 2021-06-01 15:19

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'paid'), (2, 'fulfilled'), (3, 'cancelled'), (4, 'returned')], default=0, protected=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_ammount',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
