# Generated by Django 3.2.1 on 2021-05-26 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='plants',
            field=models.ManyToManyField(blank=True, related_name='cart_plants', to='core.Plant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='plants',
            field=models.ManyToManyField(blank=True, related_name='order_plants', to='core.Plant'),
        ),
    ]
