export const USER_LOADING = "USER_LOADING";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAIL = "USER_LOADING_FAIL";
export const USER_DETAILS_UPDATED = "USER_DETAILS_UPDATED";
export const UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS";

export const UI_LOADING_START = "UI_LOADING_START";
export const UI_LOADING_END = "UI_LOADING_END";
export const UI_THEME_TOGGLE = "UI_THEME_TOGGLE";
export const SHOW_ALERT_MESSAGE = "SHOW_ALERT_MESSAGE";
export const HIDE_ALERT_MESSAGE = "HIDE_ALERT_MESSAGE";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const GET_CART = "GET_CART";
export const ADD_PLANT_TO_CART = "ADD_PLANT_TO_CART";
export const REMOVE_PLANT_FROM_CART = "REMOVE_PLANT_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

export const GET_PLANTS = "GET_PLANTS";
export const GET_SHOPS = "GET_SHOPS";
export const GET_ORDERS = "GET_ORDERS";

export const CREATE_ORDER = "CREATE_ORDER";
export const CANCEL_ORDER = "CANCEL_ORDER";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_ERROR_MESSAGE = "CREATE_ERROR_MESSAGE";
