# Generated by Django 3.2.1 on 2021-06-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='shipping_adress',
            new_name='shipping_address',
        ),
    ]
